#Configuration file

#Dir and path
Dir:
  img_dir: './images/'
  output_dir: './output_data/'
  clim_data_dir: './data/'
  clean_data_dir: './data/clean/'

#Constants
Constants:
  r_spec: 287.0
  pathway_incl: 0.0
  asc: 35.0 #ft
  climb_angle: 7.7
  margin_coef: 1.15
  #cl_default: 1.61 #default value for C_l coeff. to be found for each aircraft model

  #ISA conditions
ISA:
  isa_temp: 288.15 #K
  isa_pr: 101325 #Pa
  isa_alt: 0.0 #m

#Aircraft specifications
Aircraft:
  aircr_name: 'A320'
  aircr_engine: 'V2500-A1'
  aircr_full_m: 78000.0 #kg (can also be found in OPEN-AP)

#Airport specifications
Airport:
  airport_code: 'EGLL' #London =  EGLL , Bruxells =  EBBR
  airport_lenght: 3680.0 #m
  airport_alt: 56.0 #m

#Climate data selection
Climate:
  model: 'UKESM1-0-LL' #UKESM1-0-LL or ACCESS-ESM1-5
  months: [ 6, 7, 8 ]

#Speed spec for Take-off distance calculation
Speed:
  v0: 0.01
  decay: 'const' #please select 'exp' or 'inv' or 'exp+' or 'const'


#*************************************
#Last git commit:
# .gitignore : 1744376696
# MTOM.py : 1744640032
# README.md : 1744356544
# TODR_cl.py : 1745327240
# TODR_climate_an.py : 1745396850
# atm_cond_import.py : 1744724775
# config.yml : 1745065656
# files_manager_utils.py : 1744794607
# images : 1745396850
# output_data : 1745396850
# plots.py : 1745395646
# requirements.txt : 1745065656
# take_off_func.py : 1745395646
# tests.py : 1745327240
# utils.py : 1745065656
